---
include:
  - board: nice_nano@2.0.0
    shield: sofle_left nice_view_adapter sofle_nice_shield
    snippet: studio-rpc-usb-uart
  - board: nice_nano@2.0.0
    shield: sofle_right nice_view_adapter sofle_nice_shield
  - board: nice_nano@2.0.0
    shield: settings_reset
